# Generated by Django 5.1.1 on 2024-10-16 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.PositiveIntegerField()),
                ('local_armazenamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_vendido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_retirada', models.DateTimeField(auto_now_add=True)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecas.peca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
